# WarpMaster Konfiguration

# Datenbank Konfiguration
database:
  type: mysql # mysql oder sqlite
  host: localhost # Hostname der Datenbank  
  port: 3306 # Port der Datenbank
  database: warpmaster # Name der Datenbank
  username: root # Username der Datenbank
  password: password # Unbedingt ändern!
  pool-size: 10 # Anzahl der Verbindungen zur Datenbank
  connection-timeout: 30000 # Timeout für Verbindungen
  idle-timeout: 600000 # Timeout für inaktive Verbindungen
  max-lifetime: 1800000 # Maximale Lebensdauer der Verbindungen

# Warp Konfiguration
warps:
  default-limit: 5 # Standard-Warp-Limit pro Spieler
  cooldown: 3 # Abklingzeit in Sekunden zwischen Warp-Teleportationen

# API Konfiguration
api:
  enabled: true # API aktivieren/deaktivieren
  port: 8080 # Port der API
  host: 0.0.0.0 # Auf allen Schnittstellen lauschen
  security:
    api-key: "bitte-aendern-zu-einem-sicheren-schluessel" # API-Schlüssel zur Authentifizierung
    ip-whitelist: [] # Liste der IPs, die auf die API zugreifen dürfen (leer = alle IPs erlaubt)
      # Beispiel:
      # - "192.168.1.100"
      # - "10.0.0.0/8"
    rate-limit:
      enabled: true # Rate-Limiting aktivieren/deaktivieren
      requests-per-minute: 60 # Maximale Anfragen pro Minute pro IP

# Nachrichten
messages:
  prefix: "&8[&bWarpMaster&8] &7"
  warp-set: "&aWarp &e%name% &awurde gesetzt!"
  warp-deleted: "&cWarp &e%name% &cwurde gelöscht!"
  warp-limit-reached: "&cDu hast dein Warp-Limit von &e%limit% &cerreicht!"
  warp-not-found: "&cWarp &e%name% &cnicht gefunden!"
  warp-teleported: "&aTeleportiert zu &e%name%&a!"
  warp-already-exists: "&cDu hast bereits einen Warp mit dem Namen &e%name%&c!"
  no-permission: "&cDu hast keine Berechtigung dafür!"
  player-not-found: "&cSpieler &e%player% &cnicht gefunden!"
  cooldown-active: "&cBitte warte &e%time% &cSekunden, bevor du dich erneut warpst!"
